version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB: ${DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: >
      postgres -c logging_collector=on 
               -c log_destination=stderr 
               -c log_directory=/var/log/postgresql 
               -c log_filename=postgresql.log

  server:
    build: ./backend
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB: ${DB}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db

networks:
  default:
    driver: bridge
