version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/config:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  web1:
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_ID: SERVER-1
    depends_on:
      - db

  web2:
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_ID: SERVER-2
    depends_on:
      - db

volumes:
  postgres_data: