version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "bot_database"
      POSTGRES_USER: "bot"
      POSTGRES_PASSWORD: "change"
      POSTGRES_PORT: 5432
      SERVER_PORT: 8000
      DB: "db"
    ports:
      - "5432:5432"
    networks:
      - internal_net
    command: >
      postgres -c logging_collector=on 
               -c log_destination=stderr 
               -c log_directory=/var/log/postgresql 
               -c log_filename=postgresql.log

  server:
    build: ./backend
    environment:
      POSTGRES_DB: "bot_database"
      POSTGRES_USER: "bot"
      POSTGRES_PASSWORD: "change"
      POSTGRES_PORT: 5432
      SERVER_PORT: 8000
      DB: "db"
      DATABASE_URL: "postgresql://bot:change@db:5432/bot_database"

    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - internal_net
    restart: on-failure

networks:
  internal_net:
